# Generated by Django 6.0.3 on 2026-03-31 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_purchaserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
            ],
            options={
                'verbose_name_plural': 'Crop Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=200)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('unhelpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='savedlisting',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crop',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='crop',
            name='quality_grade',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('regular', 'Regular')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crop',
            name='type',
            field=models.CharField(choices=[('legumes', 'Legumes'), ('cereals', 'Cereals'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='crops.crop'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'buyer_id'], name='crops_purch_status_672672_idx'),
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.cropcategory'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['type', 'is_active'], name='crops_crop_type_0eaba0_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['farmer_id', 'is_active'], name='crops_crop_farmer__d92c43_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crops.crop'),
        ),
        migrations.AddField(
            model_name='review',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.purchaserequest'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['farmer_id', 'is_approved'], name='crops_revie_farmer__1914f8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='crops_revie_created_51cc65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('buyer', 'farmer', 'crop')},
        ),
    ]
