# Generated by Django 6.0.3 on 2026-03-31 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_farmers', models.PositiveIntegerField(default=0)),
                ('total_buyers', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('new_products_today', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('completed_purchases', models.PositiveIntegerField(default=0)),
                ('purchase_value_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('reviews_posted', models.PositiveIntegerField(default=0)),
                ('reports_filed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InactiveAccountFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('days_inactive', models.PositiveIntegerField(default=30)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('warning_sent', models.BooleanField(default=False)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('removal_scheduled', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('flagged', 'Flagged'), ('warning_sent', 'Warning Sent'), ('reactivated', 'Reactivated'), ('removed', 'Removed')], default='flagged', max_length=20)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_flag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inactive Account Flag',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fraud', 'Fraudulent Activity'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment/Abuse'), ('failed_transaction', 'Failed Transaction'), ('non_delivery', 'Non-Delivery'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_attachment', models.FileField(blank=True, null=True, upload_to='report_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_flagged', 'User Flagged'), ('user_suspended', 'User Suspended'), ('user_blocked', 'User Blocked'), ('user_unsuspended', 'User Unsuspended'), ('user_deleted', 'User Deleted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('review_removed', 'Review Removed'), ('message_deleted', 'Message Deleted'), ('conversation_blocked', 'Conversation Blocked'), ('farmer_removed', 'Farmer Removed'), ('admin_added', 'Admin Added'), ('settings_changed', 'Settings Changed'), ('report_resolved', 'Report Resolved'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_against', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.userreport')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FarmerActivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('products_listed', models.PositiveIntegerField(default=0)),
                ('purchase_requests_received', models.PositiveIntegerField(default=0)),
                ('purchase_requests_accepted', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_received', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('reviews_received', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reports_filed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['farmer_id', 'date'], name='admin_panel_farmer__3406a9_idx')],
                'unique_together': {('farmer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('account_created', 'Account Created'), ('account_deleted', 'Account Deleted'), ('login', 'Login'), ('password_changed', 'Password Changed'), ('verification_submitted', 'Verification Submitted'), ('review_posted', 'Review Posted'), ('message_sent', 'Message Sent'), ('purchase_completed', 'Purchase Completed'), ('account_flagged', 'Account Flagged'), ('system_alert', 'System Alert')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='admin_panel_event_t_4bce9a_idx'), models.Index(fields=['user_id', 'timestamp'], name='admin_panel_user_id_97feb7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user_id', 'status'], name='admin_panel_reporte_b36eed_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['severity', 'status'], name='admin_panel_severit_436b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin_id', 'timestamp'], name='admin_panel_admin_i_52a204_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='admin_panel_action__4671c7_idx'),
        ),
    ]
