# Generated by Django 6.0.3 on 2026-04-01 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('user_flagged', 'User Flagged'), ('user_suspended', 'User Suspended'), ('user_blocked', 'User Blocked'), ('user_unsuspended', 'User Unsuspended'), ('user_deleted', 'User Deleted'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('review_removed', 'Review Removed'), ('message_deleted', 'Message Deleted'), ('conversation_blocked', 'Conversation Blocked'), ('farmer_removed', 'Farmer Removed'), ('admin_added', 'Admin Added'), ('settings_changed', 'Settings Changed'), ('report_resolved', 'Report Resolved'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_resolved', 'Appeal Resolved'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='AccountAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_summary', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
