# Generated by Django 6.0.3 on 2026-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_farmerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='ml_model_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='risk_level',
            field=models.CharField(choices=[('trusted', 'Trusted'), ('risky', 'Risky'), ('moderate', 'Moderate')], default='moderate', max_length=20),
        ),
    ]
