# Generated by Django 6.0.3 on 2026-04-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_farmerprofile_ml_model_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID number for verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='farmer_verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
    ]
